// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UbiquoStub.Data;

#nullable disable

namespace UbiquoStub.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250526124544_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UbiquoStub.Models.Entities.RequestEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("jsonb");

                    b.Property<string>("Headers")
                        .HasColumnType("jsonb");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Uri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RequestEntity");
                });

            modelBuilder.Entity("UbiquoStub.Models.Entities.ResponseEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("jsonb");

                    b.Property<string>("Headers")
                        .HasColumnType("jsonb");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ResponseEntity");
                });

            modelBuilder.Entity("UbiquoStub.Models.Entities.Stub", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Order")
                        .HasColumnType("integer");

                    b.Property<long>("RequestId")
                        .HasColumnType("bigint");

                    b.Property<long>("ResponseId")
                        .HasColumnType("bigint");

                    b.Property<long?>("SutId")
                        .HasColumnType("bigint");

                    b.Property<string>("TestName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("ResponseId");

                    b.HasIndex("SutId");

                    b.ToTable("Stub");
                });

            modelBuilder.Entity("UbiquoStub.Models.Entities.StubResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ActualResponse")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsIntegration")
                        .HasColumnType("boolean");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StubDto")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<long>("StubId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StubId");

                    b.ToTable("StubResult");
                });

            modelBuilder.Entity("UbiquoStub.Models.Entities.Sut", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Sut");
                });

            modelBuilder.Entity("UbiquoStub.Models.Entities.Stub", b =>
                {
                    b.HasOne("UbiquoStub.Models.Entities.RequestEntity", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UbiquoStub.Models.Entities.ResponseEntity", "Response")
                        .WithMany()
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UbiquoStub.Models.Entities.Sut", null)
                        .WithMany("Stubs")
                        .HasForeignKey("SutId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Request");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("UbiquoStub.Models.Entities.StubResult", b =>
                {
                    b.HasOne("UbiquoStub.Models.Entities.Stub", "Stub")
                        .WithMany()
                        .HasForeignKey("StubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stub");
                });

            modelBuilder.Entity("UbiquoStub.Models.Entities.Sut", b =>
                {
                    b.Navigation("Stubs");
                });
#pragma warning restore 612, 618
        }
    }
}
